Fix for arch, at least
I'm a bit unsure why this worked with specter but did not work in arch.
Maybe I didn't need to wrap with-alacritty for specter? Either way, it
definitely appeared as though `inputs` wasn't needed to be passed in and
only `inputs'` was.

Here is the error I received during build time:
error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "inputs'" at /nix/store/879j7nsh0m7gxz49q9mh841xswn8g7dc-source/packages/my-nix/wrap-nixgl.nix:4, did you mean "inputs"?'